config/routes.rb
  get 'haciendas/haciendas_detalles'
  get 'haciendas/agregar_hacienda_detalle'
  post 'haciendas/guardar_hacienda_detalle'
  get 'haciendas/eliminar_hacienda_detalle'
  get 'haciendas/obtener_potreros'

  #POTREROS
  get 'potreros/index'
  post 'potreros/lista'
  get 'potreros/lista'
  get 'potreros/agregar'
  post 'potreros/guardar'
  get 'potreros/editar'
  post 'potreros/actualizar'
  get 'potreros/eliminar'
  get 'potreros/potrero_detalle'
  get 'potreros/agregar_potrero_detalle'
  post 'potreros/guardar_potrero_detalle'
  get 'potreros/eliminar_potrero_detalle'
  get 'potreros/potrero_geocerca'

  #GANADOS
  get 'ganados/index'
  post 'ganados/lista'
  get 'ganados/lista'
  get 'ganados/agregar'
  post 'ganados/guardar'
  get 'ganados/editar'
  post 'ganados/actualizar'
  get 'ganados/eliminar'
  get 'ganados/ganado_detalle'
  get 'ganados/obtener_etapa_ganado'
  get 'ganados/buscar_rp_padre'
  get 'ganados/buscar_rp_madre'
  get 'ganados/agregar_control_sanitario'
  post 'ganados/guardar_control_sanitario'
  get 'ganados/eliminar_control_sanitario'
  get 'ganados/agregar_control_alimentacion'
  post 'ganados/guardar_control_alimentacion'
  get 'ganados/eliminar_control_alimentacion'
  get 'ganados/adjuntar_archivo'
  post 'ganados/guardar_archivo_adjunto'
  get 'ganados/agregar_celo'
  post 'ganados/guardar_celo'
  get 'ganados/buscar_ganado'
  get 'ganados/agregar_lote_ganado'
  post 'ganados/guardar_lote_ganado'
  get 'ganados/marcar_con_enfermedad'
  post 'ganados/guardar_ganado_enfermedad'
  get 'ganados/marcar_como_muerto'
  post 'ganados/guardar_ganado_muerto'
  get 'ganados/marcar_como_produccion'
  get 'ganados/historial_ganado'


  #MEDICAMENTOS
  get 'medicamentos/index'
  post 'medicamentos/lista'
  get 'medicamentos/lista'
  get 'medicamentos/agregar'
  post 'medicamentos/guardar'
  get 'medicamentos/editar'
  post 'medicamentos/actualizar'
  get 'medicamentos/eliminar'
  get 'medicamentos/buscar_medicamento'
  get 'medicamentos/medicamento_detalle'
  get 'medicamentos/agregar_medicamento_detalle'
  post 'medicamentos/guardar_medicamento_detalle'
  get 'medicamentos/eliminar_medicamento_detalle'
  get 'medicamentos/dar_baja_medicamento'
  post 'medicamentos/guardar_baja_medicamento'

  #ALIMENTOS
  get 'alimentaciones/index'
  post 'alimentaciones/lista'
  get 'alimentaciones/lista'
  get 'alimentaciones/agregar'
  post 'alimentaciones/guardar'
  get 'alimentaciones/editar'
  post 'alimentaciones/actualizar'
  get 'alimentaciones/eliminar'
  get 'alimentaciones/buscar_alimentacion'
  get 'alimentaciones/alimentacion_detalle'
  get 'alimentaciones/agregar_alimentacion_detalle'
  post 'alimentaciones/guardar_alimentacion_detalle'
  get 'alimentaciones/eliminar_alimentacion_detalle'

  #CELOS
  get 'celos/index'
  post 'celos/lista'
  get 'celos/lista'
  get 'celos/agregar'
  post 'celos/guardar'
  get 'celos/editar'
  post 'celos/actualizar'
  get 'celos/eliminar'
  get 'celos/celos_detalles'
  get 'celos/cambiar_estado_a_en_proceso_fecundacion'
  get 'celos/cambiar_estado_a_en_reproduccion'
  get 'celos/cambiar_estado_a_celo_perdido'
  post 'celos/guardar_cambiar_estado_a_en_proceso_fecundacion'
  post 'celos/guardar_cambiar_estado_a_en_reproduccion'
  post 'celos/guardar_cambiar_estado_a_celo_perdido'
  get 'celos/buscar_ganado_reproductor'
  get 'celos/buscar_esperma_reproductor'

  #REPRODUCCIONES
  get 'reproducciones/index'
  post 'reproducciones/lista'
  get 'reproducciones/lista'
  get 'reproducciones/agregar'
  post 'reproducciones/guardar'
  get 'reproducciones/eliminar'
  get 'reproducciones/reproducciones_detalles'
  get 'reproducciones/cambiar_estado_reproduccion'
  get 'reproducciones/cambiar_estado_reproduccion_a_reproduccion_perdido'
  post 'reproducciones/guardar_estado_reproduccion_a_reproduccion_perdido'
  get 'reproducciones/cambiar_estado_reproduccion_a_reproduccion_finalizada'
  post 'reproducciones/guardar_estado_reproduccion_a_reproduccion_finalizada'
  get 'reproducciones/buscar_ganado_reproductor'
  get 'reproducciones/buscar_esperma_reproductor'
  get 'reproducciones/buscar_ganado_estado_celo'


  #ESTADOS GANADOS
  get 'estados_ganados/index'
  post 'estados_ganados/lista'
  get 'estados_ganados/lista'
  get 'estados_ganados/agregar'
  post 'estados_ganados/guardar'
  get 'estados_ganados/editar'
  post 'estados_ganados/actualizar'
  get 'estados_ganados/eliminar'
  get 'estados_ganados/buscar_estado_ganado'

  #EMPRESAS TRANSPORTES
  get 'empresas_transportes/index'
  post 'empresas_transportes/lista'
  get 'empresas_transportes/lista'
  get 'empresas_transportes/agregar'
  post 'empresas_transportes/guardar'
  get 'empresas_transportes/editar'
  post 'empresas_transportes/actualizar'
  get 'empresas_transportes/eliminar'
  get 'empresas_transportes/buscar_empresa_transporte'

  #PROVEEDORES GANADOS
  get 'proveedores_ganados/index'
  post 'proveedores_ganados/lista'
  get 'proveedores_ganados/lista'
  get 'proveedores_ganados/agregar'
  post 'proveedores_ganados/guardar'
  get 'proveedores_ganados/editar'
  post 'proveedores_ganados/actualizar'
  get 'proveedores_ganados/eliminar'
  get 'proveedores_ganados/buscar_proveedor_ganado'

  #ESPERMAS
  get 'espermas/index'
  post 'espermas/lista'
  get 'espermas/lista'
  get 'espermas/agregar'
  post 'espermas/guardar'
  get 'espermas/editar'
  post 'espermas/actualizar'
  get 'espermas/eliminar'
  get 'espermas/esperma_detalle'
  get 'espermas/buscar_ganado'
  get 'espermas/adjuntar_archivo_reproductor'
  post 'espermas/guardar_archivo_adjunto'

  #CONTROLES GANADOS
  get 'controles_ganados/index'
  post 'controles_ganados/lista'
  get 'controles_ganados/lista'
  get 'controles_ganados/agregar'
  post 'controles_ganados/guardar'
  get 'controles_ganados/editar'
  post 'controles_ganados/actualizar'
  get 'controles_ganados/eliminar'
  get 'controles_ganados/buscar_ganado'
  get 'controles_ganados/crear_lote_ganado'
  post 'controles_ganados/crear_lote_ganado'
  post 'controles_ganados/lista_ganado'
  get 'controles_ganados/lista_ganado'
  get 'controles_ganados/agregar_ganado_lote'
  get 'controles_ganados/eliminar_ganado_lote'
  get 'controles_ganados/seleccionar_lote'
  post 'controles_ganados/eliminar_lote'
  get 'controles_ganados/obtener_resumen_control_ganado'
  get 'controles_ganados/imprimir_resumen_control_ganado'
  post 'controles_ganados/imprimir_resumen'
  

  #CONTROLES ALIMENTACIONES
  get 'controles_alimentaciones/index'
  post 'controles_alimentaciones/lista'
  get 'controles_alimentaciones/lista'
  get 'controles_alimentaciones/agregar'
  post 'controles_alimentaciones/guardar'
  get 'controles_alimentaciones/editar'
  post 'controles_alimentaciones/actualizar'
  get 'controles_alimentaciones/eliminar'
  get 'controles_alimentaciones/buscar_ganado'
  get 'controles_alimentaciones/crear_lote_ganado'
  post 'controles_alimentaciones/crear_lote_ganado'
  post 'controles_alimentaciones/lista_ganado'
  get 'controles_alimentaciones/lista_ganado'
  get 'controles_alimentaciones/agregar_ganado_lote'
  get 'controles_alimentaciones/eliminar_ganado_lote'
  get 'controles_alimentaciones/seleccionar_lote'
  post 'controles_alimentaciones/eliminar_lote'


  #GANADOS ENTRADAS
  get 'ganados_entradas/index'
  post 'ganados_entradas/lista'
  get 'ganados_entradas/lista'
  get 'ganados_entradas/agregar_entrada_ganado'
  post 'ganados_entradas/guardar_entrada_ganado'
  get 'ganados_entradas/eliminar_entrada_ganado'
  get 'ganados_entradas/buscar_proveedor'
  get 'ganados_entradas/editar_entrada_ganado'
  post 'ganados_entradas/actualizar_entrada_ganado'
  get 'ganados_entradas/cambiar_estado_entrada_ganado_a_finalizado'
  post 'ganados_entradas/guardar_estado_entrada_ganado_a_finalizado'

  #GANADOS SALIDAS
  get 'ganados_salidas/index'
  post 'ganados_salidas/lista'
  get 'ganados_salidas/lista'
  get 'ganados_salidas/agregar'
  post 'ganados_salidas/guardar'
  get 'ganados_salidas/editar'
  post 'ganados_salidas/actualizar'
  get 'ganados_salidas/eliminar_salida_ganado'
  get 'ganados_salidas/buscar_ganado'
  get 'ganados_salidas/crear_lote_ganado'
  post 'ganados_salidas/crear_lote_ganado'
  post 'ganados_salidas/lista_ganado'
  get 'ganados_salidas/lista_ganado'
  get 'ganados_salidas/agregar_ganado_lote'
  get 'ganados_salidas/eliminar_ganado_lote'
  get 'ganados_salidas/seleccionar_lote'
  post 'ganados_salidas/eliminar_lote'
  get 'ganados_salidas/buscar_cliente'
  get 'ganados_salidas/cambiar_estado_salida_a_finalizado'
  get 'ganados_salidas/seleccionar_lote_a_finalizar'
  post 'ganados_salidas/finalizar_lote_ganado'

  #GANADOS ENFERMOS
  get 'ganados_enfermos/index'
  post 'ganados_enfermos/lista'
  get 'ganados_enfermos/lista'
  get 'ganados_enfermos/eliminar'
  get 'ganados_enfermos/ganado_enfermo_detalle'
  get 'ganados_enfermos/agregar_control_sanitario'
  post 'ganados_enfermos/guardar_control_sanitario'
  get 'ganados_enfermos/eliminar_control_sanitario'
  get 'ganados_enfermos/editar_ganado_enfermo'
  post 'ganados_enfermos/actualizar_ganado_enfermo'
  get 'ganados_enfermos/cambiar_estado_a_recuperado'
  get 'ganados_enfermos/cambiar_estado_a_muerto'
  post 'ganados_enfermos/guardar_estado_ganado_muerto'
  get 'ganados_enfermos/adjuntar_archivo'
  post 'ganados_enfermos/guardar_archivo_adjunto'

  #ALTAS PRODUCCIONES
  get 'altas_producciones/index'
  post 'altas_producciones/lista'
  get 'altas_producciones/lista'
  get 'altas_producciones/alta_produccion_detalle'
  get 'altas_producciones/agregar_alta_produccion_detalle'
  post 'altas_producciones/guardar_alta_produccion_detalle'
  get 'altas_producciones/eliminar_alta_produccion_detalle'
  get 'altas_producciones/marcar_desactivado'
  get 'altas_producciones/agregar_produccion_lote'
  get 'altas_producciones/eliminar_produccion_lote'
  get 'altas_producciones/verificar_tabla_temporal'
  get 'altas_producciones/agregar_alta_produccion_queso'
  post 'altas_producciones/guardar_alta_produccion_queso'

app/helpers/reproducciones_helper.rb
module ReproduccionesHelper

  def link_to_editar_reproduccion(reproduccion_id)

      render partial: 'link_to_editar_reproduccion', locals: { reproduccion_id: reproduccion_id }
      
  end

  def link_to_reproduccion_detalle(reproduccion_id)

    render partial: 'link_to_reproduccion_detalle', locals: { reproduccion_id: reproduccion_id}

  end

  def link_to_cambiar_estado_reproduccion_a_reproduccion_prenhada(reproduccion_id)

    render partial: 'link_to_cambiar_estado_reproduccion_a_reproduccion_prenhada', locals: {reproduccion_id: reproduccion_id}

  end

  def link_to_cambiar_estado_reproduccion_a_reproduccion_finalizada(reproduccion_id)

    render partial: 'link_to_cambiar_estado_reproduccion_a_reproduccion_finalizada', locals: {reproduccion_id: reproduccion_id}

  end


  def link_to_cambiar_estado_reproduccion_a_reproduccion_perdido(reproduccion_id)

    render partial: 'link_to_cambiar_estado_reproduccion_a_reproduccion_perdido', locals: {reproduccion_id: reproduccion_id}

  end
  
end

app/views/reproducciones/_editar.html.erb
<div class="modal-dialog" style="text-align:left;">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Editar Potrero</h4>
      
    </div>

    <%= form_for @potrero, remote: true, url: potreros_actualizar_url, html: { id: "form-editar-potrero" }, method: 'POST' do |f| %>

      <%= hidden_field_tag :id, @potrero.id %>
      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Hacienda #{attr_requerido}".html_safe, id: "lbl-hacienda" %></div>
          <div class="col-sm-7"><%= collection_select :potrero, :hacienda_id, Hacienda.orden_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= f.label :descripcion, "Descripción #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm',style:"text-transform:uppercase;" %></div>
          <div class="col-sm-1"></div><br /><br />  

           <div class="col-sm-4"><%= f.label :hectarea, "Hectáreas #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :hectareas, :onkeypress=> "return isNumberKey(event)", class: 'form-control input-sm',style:"text-transform:uppercase;", :maxlength=> 12 %></div>
          <div class="col-sm-1"></div><br /><br />

           <div class="col-sm-4"><%= label_tag nil, "Observación".html_safe, id: "lbl-observacion" %></div>
          <div class="col-sm-7">
          <%= f.text_area :observacion,  class: 'form-control input-sm' , :size =>"25x3", maxlength: "510" %>
          </div>
         <div class="col-sm-1"></div><br /><br />


        
        
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Actualizar", class: "btn btn-primary", id: "btn-actualizar-potrero" %>
          
      </div>

    <% end %>

  </div>
</div>

<style type="text/css">

  #form-editar-potrero label, #form-editar-potrero input[type='text'], #form-editar-potrero select { float:left; margin-top:5px;}
  #form-editar-potrero br {clear:both; }
  #form-editar-potrero label { width:200px;font-size:12px;margin-top:10px;}
 

</style>

<script type="text/javascript">

  setTimeout(function(){ 
    $("#persona_documento_persona").focus();
  }, 1000);
  aplicar_datepicker2();
  
</script>

app/views/reproducciones/_link_to_cambiar_estado_reproduccion_a_reproduccion_finalizada.html.erb
<%= link_to icon_reproduccion, "#", id: "link-to-cambiar-estado-reproduccion-#{reproduccion_id}", class: 'btn btn-success btn-xs', title: 'Haga click aquí para Finalizar la Reproduccion del animal y agregar el nuevo ejemplar nacido.', onclick: "$('.modal').html('');return false;" %>
<%= modal_window( window_id: "modal-window-cambiar-estado-reproduccion-#{reproduccion_id}", link_to_id: "#link-to-cambiar-estado-reproduccion-#{reproduccion_id}", url: reproducciones_cambiar_estado_reproduccion_a_reproduccion_finalizada_path( window_id: "modal-window-cambiar-estado-reproduccion-#{reproduccion_id}", reproduccion_id: reproduccion_id) )%>

app/views/reproducciones/_link_to_cambiar_estado_reproduccion_a_reproduccion_perdido.html.erb
<%= link_to icon_perdido, "#", id: "link-to-cambiar-estado-reproduccion-a-perdido-#{reproduccion_id}", class: 'btn btn-danger btn-xs', title: 'Haga click aquí cambiar el estado de Reproducción a Reproducción Perdida (Aborto).', onclick: "$('.modal').html('');return false;" %>
<%= modal_window( window_id: "modal-window-cambiar-estado-reproduccion-a-perdido-#{reproduccion_id}", link_to_id: "#link-to-cambiar-estado-reproduccion-a-perdido-#{reproduccion_id}", url: reproducciones_cambiar_estado_reproduccion_a_reproduccion_perdido_path( window_id: "modal-window-cambiar-estado-reproduccion-a-perdido-#{reproduccion_id}", reproduccion_id: reproduccion_id) )%>

app/views/reproducciones/_link_to_reproduccion_detalle.html.erb
<%= link_to icon_detalles, "#", id: "link-to-reproduccion-detalle-#{reproduccion_id}", class: 'btn btn-success btn-xs', title: 'Haga click para ver los detalles de la Reproducción', onclick: "$('.modal').html('');return false;" %>

<script type="text/javascript">

  $("#link-to-reproduccion-detalle-<%= reproduccion_id %>").bind('click', function(){

    var contenido = $.trim($("#reproduccion-detalle-<%= reproduccion_id %>").html());

    $(".reproduccion-detalle").html('');

    if(contenido.length == 0){

    $(this).parent().parent().after("<tr id='reproduccion-detalle-<%= reproduccion_id %>' class='reproduccion-detalle'><td colspan='12' style='text-align:center;'><i class='fa fa-refresh fa-spin'></i> Cargando...</td></tr>")

      $.ajax({

        type: 'GET',
        url: '<%= url_for(reproducciones_reproducciones_detalles_path) %>',  
        data: { reproduccion_id: <%= reproduccion_id %>},
        dataType: 'script'
        
      })

    }
    
    return false;
  })

</script>

app/views/reproducciones/cambiar_estado_reproduccion.js.erb
<% if @guardado_ok %>
   
  $("#form_buscar_reproduccion_id").val('<%= @reproduccion.id %>');
  $("#form_buscar_reproduccion_ganado_rfid").val('');
  $("#form_buscar_reproduccion_ganado_nombre").val('');
  $("#form_buscar_reproduccion_ganado_rp").val('');
 
  
  setTimeout(function(){ 

    
    swal("Reproducción","Estado de Reproducción modificado exitosamente!", "success");
    $("#form-buscar-reproduccion").submit();
    
  }, 2000);


<% else %>
  
  swal("Reproducción", "Error al guardar el cambio de estado de Reproducción.<%=@msg%> Intente más tarde","error");

<% end %>

app/views/reproducciones/cambiar_estado_reproduccion_a_reproduccion_finalizada.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'cambiar_estado_a_reproduccion_finalizada')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/reproducciones/cambiar_estado_reproduccion_a_reproduccion_perdido.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'cambiar_estado_reproduccion_a_reproduccion_perdido')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/reproducciones/index.html.erb
<%= javascript_include_tag "sweetalert.min" %>
<%= stylesheet_link_tag "sweetalert" %>
<div>

  <div class="col-sm-12" style="border-bottom: 2px solid #b6b6b6;margin-bottom:5px;padding:0px;">
    <h3 style="float:left;margin-top:5px;">Reproducciones Ganados</h3>
    <%= link_to "<i class='glyphicon glyphicon-plus-sign'></i> agregar reproducción".html_safe, "#", id: "link-to-agregar-reproduccion", class: "btn btn-primary pull-right", style: "float:right;margin-left:10px;", onclick: "$('.modal').html('');return false;" %>
    <%= modal_window( window_id: "modal-window-agregar-reproduccion", link_to_id: "#link-to-agregar-reproduccion", url: reproducciones_agregar_path( window_id: "modal-window-agregar-reproduccion") )%>
    
  </div>
  
</div>

<div style="clear:both;"></div>
 
<div class="table-responsive" id="table-reproduccion">

  <table class="table table-small-font table-bordered table-striped" style="font-size:11px;">
   
    <thead>

      <%= form_tag reproducciones_lista_path, remote: true, id: "form-buscar-reproduccion"  do  %>

        <tr>

          <th >
            <span>ID</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_reproduccion_id, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_id');"><i class="fa fa-times"></i></span>
            </div>
          </th>

          <th >
            <span>Ganado RFID</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_reproduccion_ganado_rfid, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_ganado_rfid');"><i class="fa fa-times"></i></span>
            </div>
          </th>
          
           <th >
            <span>Ganado Nombre</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_reproduccion_ganado_nombre, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_ganado_nombre');"><i class="fa fa-times"></i></span>
            </div>
          </th>

          <th >
            <span>Ganado RP</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_reproduccion_ganado_rp, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_ganado_rp');"><i class="fa fa-times"></i></span>
            </div>
          </th>

          <th>
            <div><%= label_tag nil, "Fecha Reproducción".html_safe %></div>
              <div class='input-group date'>
                <%= text_field_tag :form_buscar_reproduccion_fecha_reproduccion, nil, class: 'form-control input-sm' %>
                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_fecha_reproduccion');"><i class="fa fa-times"></i></span>
              </div>
         </th>

         <th>
            <div><%= label_tag nil, "Fecha Concepción".html_safe %></div>
              <div class='input-group date'>
                <%= text_field_tag :form_buscar_reproduccion_fecha_concepcion, nil, class: 'form-control input-sm' %>
                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_fecha_concepcion');"><i class="fa fa-times"></i></span>
              </div>
         </th>

          <th >
            <span>Reproducción Descripción</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_reproduccion_descripcion, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_descripcion');"><i class="fa fa-times"></i></span>
            </div>
          </th>
          
          <th>
              <span>Hacienda</span>
            <div class="input-group input-group-sm">
              <%= collection_select :form_buscar_reproduccion, :hacienda_id, Hacienda.orden_descripcion, :id, :descripcion, { include_blank: true}, {:class => 'form-control input-sm', style: "font-size:9px;"} %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_hacienda_id');"><i class="fa fa-times"></i></span>
            </div>
          </th> 

          <th >
              <span>Tipo Reproducción</span>
            <div class="input-group input-group-sm">
              <%= collection_select :form_buscar_reproduccion, :tipo_concepcion_id, TipoConcepcion.orden_01, :id, :descripcion, { include_blank: true}, {:class => 'form-control input-sm', style: "font-size:9px;"} %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_tipo_concepcion_id');"><i class="fa fa-times"></i></span>
            </div>
          </th> 

           <th >
              <span>Estado Reproducción</span>
            <div class="input-group input-group-sm">
              <%= collection_select :form_buscar_reproduccion, :estado_reproduccion_id, EstadoReproduccion.orden_01, :id, :descripcion, { include_blank: true}, {:class => 'form-control input-sm', style: "font-size:9px;"} %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-reproduccion', '#form_buscar_reproduccion_estado_reproduccion_id');"><i class="fa fa-times"></i></span>
            </div>
          </th> 


          <th ></th>

        </tr>

        <% end %>

      </thead> 

    <tbody id="reproducciones-lista"></tbody>
  
  </table>

</div>




<script type="text/javascript">

  $("#form-buscar-reproduccion").submit();

  //---------------------------- RECUPERANDO DATOS ----------------------------//
  $("#form-buscar-reproduccion").bind("submit", function () {

    var valido = true;
    if($("#form_buscar_reproduccion_descripcion").val().length !== 0 ){
      valido = false;
      if(($("#form_buscar_reproduccion_descripcion").val().replace(/\s/g,'')).length > 2){        
        valido = true;
      }else{
        valido = false;
                 
        $(".nmb").html('*Ingrese minimo 3(tres) carácteres para cada caja de texto');
        $(".nmb").attr({'style':'color: red;font-size: 8px;'});      
      }      
    }
      
    if(valido){
      
    $(".nmb").html('');       
    $("#celos-lista").html("<%= escape_javascript("<tr><td colspan='9' style='text-align:center;'>#{image_tag('ajax-loader0.gif')}</td></tr>").html_safe %>")      
    }

    

  })
 
  //---------------------------------------------------------------------------//
  //---------------------------- BUSCAR PERSONAS-------- -------------------------//
  $("#table-reproduccion input, #table-reproduccion select").bind('change', function () {
      $.ajaxQ.abortAll();
      $("#form-buscar-reproduccion").submit();

  })
  //----------------------------------------------------------------------------//
  //----------------------------INICIO -----------------------------------------//
  aplicar_datepicker();
  
  //----------------------------------------------------------------------------//
  
</script>

<style>
    /*INTRO.JS*/
    .introjs-helperNumberLayer{
        width: 23px;
        height: 23px;
        padding: 0px;
    }

    #start-tour{
        cursor: pointer;
    }

    #form-buscar-reproduccion table th { background:#e6e6e6;}
    #form-buscar-reproduccion table th span.limpiar { background:#fff;}

</style>

app/views/reproducciones/lista.js.erb
$("#reproducciones-lista").html("<%= escape_javascript(render partial: "lista", locals: { reproducciones: @reproducciones }) %>");