config/routes.rb
  get 'notificaciones_personas/lista'
  get 'notificaciones_personas/agregar'
  post 'notificaciones_personas/guardar'
  get 'notificaciones_personas/eliminar'
  get 'notificaciones_personas/editar'
  post 'notificaciones_personas/actualizar'
  get 'notificaciones_personas/index'
  get 'notificaciones_personas/activar_notificacion'


#GANADOS FAENAS
  get 'ganados_faenas/index'
  post 'ganados_faenas/lista'
  get 'ganados_faenas/lista'
  get 'ganados_faenas/agregar'
  post 'ganados_faenas/guardar'
  get 'ganados_faenas/eliminar_ganado_faena'
  get 'ganados_faenas/crear_lote_ganado'
  post 'ganados_faenas/crear_lote_ganado'
  post 'ganados_faenas/lista_ganado'
  get 'ganados_faenas/lista_ganado'
  get 'ganados_faenas/agregar_ganado_lote'
  get 'ganados_faenas/eliminar_ganado_lote'
  get 'ganados_faenas/seleccionar_lote'
  post 'ganados_faenas/eliminar_lote'
  get 'ganados_faenas/buscar_cliente'
  get 'ganados_faenas/buscar_ganado'
  get 'ganados_faenas/ganado_faena_detalle'

#INFO GASTOS
  get 'info_gastos/index'
  post 'info_gastos/lista'
  get 'info_gastos/lista'
  get 'info_gastos/exportar_pdf'

#INFO COMPRAS
  get 'info_compras/index'
  post 'info_compras/lista'
  get 'info_compras/lista'
  get 'info_compras/exportar_pdf'
  post 'info_compras/exportar_pdf'

#INFO VENTAS
  get 'info_ventas/index'
  post 'info_ventas/lista'
  get 'info_ventas/lista'
  get 'info_ventas/exportar_pdf'

#GANADOS MUERTOS
  get 'ganados_muertos/index'
  post 'ganados_muertos/lista'
  get 'ganados_muertos/lista'
  get 'ganados_muertos/exportar_pdf'
  
#CARGOS
  post 'cargos/lista'
  get 'cargos/lista'
  get 'cargos/agregar'
  post 'cargos/guardar'
  get 'cargos/eliminar'
  get 'cargos/editar'
  post 'cargos/actualizar'
  get 'cargos/index'

#REMUNERACIONES EXTRAS
  post 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/agregar'
  post 'pagos_remuneraciones_extras/guardar'
  get 'pagos_remuneraciones_extras/eliminar'
  get 'pagos_remuneraciones_extras/editar'
  post 'pagos_remuneraciones_extras/actualizar'
  get 'pagos_remuneraciones_extras/index'

#DESCUENTOS
  post 'pagos_descuentos/lista'
  get 'pagos_descuentos/lista'
  get 'pagos_descuentos/agregar'
  post 'pagos_descuentos/guardar'
  get 'pagos_descuentos/eliminar'
  get 'pagos_descuentos/editar'
  post 'pagos_descuentos/actualizar'
  get 'pagos_descuentos/index'

#ADELANTOS
  post 'pagos_adelantos/lista'
  get 'pagos_adelantos/lista'
  get 'pagos_adelantos/agregar'
  post 'pagos_adelantos/guardar'
  get 'pagos_adelantos/eliminar'
  get 'pagos_adelantos/editar'
  post 'pagos_adelantos/actualizar'
  get 'pagos_adelantos/index'

#PAGOS DE SALARIOS
  get 'pagos_salarios/index'
  post 'pagos_salarios/lista'
  get 'pagos_salarios/lista'
  get 'pagos_salarios/agregar'
  post 'pagos_salarios/guardar'
  get 'pagos_salarios/eliminar'
  get 'pagos_salarios/salario_detalle'
  
  #MATERIALES
  get 'materiales/index'
  post 'materiales/lista'
  get 'materiales/lista'
  get 'materiales/agregar'
  post 'materiales/guardar'
  get 'materiales/editar'
  post 'materiales/actualizar'
  get 'materiales/eliminar'
  get 'materiales/buscar_material'
  get 'materiales/material_detalle'
  get 'materiales/agregar_material_detalle'
  post 'materiales/guardar_material_detalle'
  get 'materiales/eliminar_material_detalle'


  #TRABAJOS
  get 'trabajos/index'
  post 'trabajos/lista'
  get 'trabajos/lista'
  get 'trabajos/agregar'
  post 'trabajos/guardar'
  get 'trabajos/editar'
  post 'trabajos/actualizar'
  get 'trabajos/eliminar'


  #ORDENES TRABAJOS
  get 'ordenes_trabajos/index'
  post 'ordenes_trabajos/lista'
  get 'ordenes_trabajos/lista'
  get 'ordenes_trabajos/agregar'
  post 'ordenes_trabajos/guardar'
  get 'ordenes_trabajos/editar'
  post 'ordenes_trabajos/actualizar'
  get 'ordenes_trabajos/eliminar'
  get 'ordenes_trabajos/trabajos_detalles'
  get 'ordenes_trabajos/agregar_material_trabajo'
  post 'ordenes_trabajos/guardar_material_trabajo'
  get 'ordenes_trabajos/eliminar_material_trabajo'


#REGISTROS DE GASTOS
  post 'registros_gastos/lista'
  get 'registros_gastos/lista'
  get 'registros_gastos/agregar'
  post 'registros_gastos/guardar'
  get 'registros_gastos/eliminar'
  get 'registros_gastos/editar'
  post 'registros_gastos/actualizar'
  get 'registros_gastos/index'
  

#PERSONALES
  post 'personales/lista'
  get 'personales/lista'
  get 'personales/agregar'
  post 'personales/guardar'
  get 'personales/eliminar'
  get 'personales/editar'
  post 'personales/actualizar'
  get 'personales/index'
  get 'personales/buscar_personal'

  #RAZAS
  get 'razas/index'
  post 'razas/lista'
  get 'razas/lista'
  get 'razas/agregar'
  post 'razas/guardar'
  get 'razas/editar'
  post 'razas/actualizar'
  get 'razas/eliminar'
  get 'razas/buscar_raza'

  #HACIENDAS
  get 'haciendas/index'
  post 'haciendas/lista'
  get 'haciendas/lista'
  get 'haciendas/agregar'
  post 'haciendas/guardar'
  get 'haciendas/editar'
  post 'haciendas/actualizar'
  get 'haciendas/eliminar'
  get 'haciendas/buscar_jurisdiccion'
  get 'haciendas/haciendas_detalles'
  get 'haciendas/agregar_hacienda_detalle'
  post 'haciendas/guardar_hacienda_detalle'
  get 'haciendas/eliminar_hacienda_detalle'
  get 'haciendas/obtener_potreros'

  #POTREROS
  get 'potreros/index'
  post 'potreros/lista'
  get 'potreros/lista'
  get 'potreros/agregar'
  post 'potreros/guardar'
  get 'potreros/editar'
  post 'potreros/actualizar'
  get 'potreros/eliminar'
  get 'potreros/potrero_detalle'
  get 'potreros/agregar_potrero_detalle'
  post 'potreros/guardar_potrero_detalle'
  get 'potreros/eliminar_potrero_detalle'
  get 'potreros/potrero_geocerca'

  #GANADOS
  get 'ganados/index'
  post 'ganados/lista'
  get 'ganados/lista'
  get 'ganados/agregar'
  post 'ganados/guardar'
  get 'ganados/editar'
  post 'ganados/actualizar'
  get 'ganados/eliminar'
  get 'ganados/ganado_detalle'
  get 'ganados/obtener_etapa_ganado'
  get 'ganados/buscar_rp_padre'
  get 'ganados/buscar_rp_madre'
  get 'ganados/agregar_control_sanitario'
  post 'ganados/guardar_control_sanitario'
  get 'ganados/eliminar_control_sanitario'
  get 'ganados/agregar_control_alimentacion'
  post 'ganados/guardar_control_alimentacion'
  get 'ganados/eliminar_control_alimentacion'
  get 'ganados/adjuntar_archivo'
  post 'ganados/guardar_archivo_adjunto'
  get 'ganados/agregar_celo'
  post 'ganados/guardar_celo'
  get 'ganados/buscar_ganado'
  get 'ganados/agregar_lote_ganado'
  post 'ganados/guardar_lote_ganado'
  get 'ganados/marcar_con_enfermedad'
  post 'ganados/guardar_ganado_enfermedad'
  get 'ganados/marcar_como_muerto'
  post 'ganados/guardar_ganado_muerto'
  get 'ganados/marcar_como_produccion'
  get 'ganados/historial_ganado'


  #MEDICAMENTOS
  get 'medicamentos/index'
  post 'medicamentos/lista'
  get 'medicamentos/lista'
  get 'medicamentos/agregar'
  post 'medicamentos/guardar'
  get 'medicamentos/editar'
  post 'medicamentos/actualizar'
  get 'medicamentos/eliminar'
  get 'medicamentos/buscar_medicamento'
  get 'medicamentos/medicamento_detalle'
  get 'medicamentos/agregar_medicamento_detalle'
  post 'medicamentos/guardar_medicamento_detalle'
  get 'medicamentos/eliminar_medicamento_detalle'
  get 'medicamentos/dar_baja_medicamento'
  post 'medicamentos/guardar_baja_medicamento'

  #ALIMENTOS
  get 'alimentaciones/index'
  post 'alimentaciones/lista'
  get 'alimentaciones/lista'
  get 'alimentaciones/agregar'
  post 'alimentaciones/guardar'
  get 'alimentaciones/editar'
  post 'alimentaciones/actualizar'
  get 'alimentaciones/eliminar'
  get 'alimentaciones/buscar_alimentacion'
  get 'alimentaciones/alimentacion_detalle'
  get 'alimentaciones/agregar_alimentacion_detalle'
  post 'alimentaciones/guardar_alimentacion_detalle'
  get 'alimentaciones/eliminar_alimentacion_detalle'

  #CELOS
  get 'celos/index'
  post 'celos/lista'
  get 'celos/lista'
  get 'celos/agregar'
  post 'celos/guardar'
  get 'celos/editar'
  post 'celos/actualizar'
  get 'celos/eliminar'
  get 'celos/celos_detalles'
  get 'celos/cambiar_estado_a_en_proceso_fecundacion'
  get 'celos/cambiar_estado_a_en_reproduccion'
  get 'celos/cambiar_estado_a_celo_perdido'
  post 'celos/guardar_cambiar_estado_a_en_proceso_fecundacion'
  post 'celos/guardar_cambiar_estado_a_en_reproduccion'
  post 'celos/guardar_cambiar_estado_a_celo_perdido'
  get 'celos/buscar_ganado_reproductor'
  get 'celos/buscar_esperma_reproductor'

  #REPRODUCCIONES
  get 'reproducciones/index'
  post 'reproducciones/lista'
  get 'reproducciones/lista'
  get 'reproducciones/agregar'
  post 'reproducciones/guardar'
  get 'reproducciones/eliminar'
  get 'reproducciones/reproducciones_detalles'
  get 'reproducciones/cambiar_estado_reproduccion'
  get 'reproducciones/cambiar_estado_reproduccion_a_reproduccion_perdido'
  post 'reproducciones/guardar_estado_reproduccion_a_reproduccion_perdido'
  get 'reproducciones/cambiar_estado_reproduccion_a_reproduccion_finalizada'
  post 'reproducciones/guardar_estado_reproduccion_a_reproduccion_finalizada'
  get 'reproducciones/buscar_ganado_reproductor'
  get 'reproducciones/buscar_esperma_reproductor'
  get 'reproducciones/buscar_ganado_estado_celo'


  #ESTADOS GANADOS
  get 'estados_ganados/index'
  post 'estados_ganados/lista'
  get 'estados_ganados/lista'
  get 'estados_ganados/agregar'
  post 'estados_ganados/guardar'
  get 'estados_ganados/editar'
  post 'estados_ganados/actualizar'
  get 'estados_ganados/eliminar'
  get 'estados_ganados/buscar_estado_ganado'

  #EMPRESAS TRANSPORTES
  get 'empresas_transportes/index'
  post 'empresas_transportes/lista'
  get 'empresas_transportes/lista'
  get 'empresas_transportes/agregar'
  post 'empresas_transportes/guardar'
  get 'empresas_transportes/editar'
  post 'empresas_transportes/actualizar'
  get 'empresas_transportes/eliminar'
  get 'empresas_transportes/buscar_empresa_transporte'

  #PROVEEDORES GANADOS
  get 'proveedores_ganados/index'
  post 'proveedores_ganados/lista'

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base

  self.table_name="trabajos"
  attr_accessible :id, :descripcion, :created_at, :updated_at

  scope :orden_01, -> {order("id")}
  scope :orden_descripcion, -> {order("descripcion")}

end

app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController

  before_filter :require_usuario

  def index
  end

  def lista

    cond = []
    args = []

    if params[:form_buscar_trabajos_id].present?

      cond << "id = ?"
      args << params[:form_buscar_trabajos_id]

    end

 
    if params[:form_buscar_trabajos_descripcion].present?

      cond << "descripcion ilike ?"
      args << "%#{params[:form_buscar_trabajos_descripcion]}%"

    end


    cond = cond.join(" and ").lines.to_a + args if cond.size > 0

    if cond.size > 0
 
      @trabajos =  Trabajo.orden_01.where(cond).paginate(per_page: 12, page: params[:page])
      @total_encontrados = Trabajo.where(cond).count

    else

      @trabajos = Trabajo.orden_01.paginate(per_page: 12, page: params[:page])
      @total_encontrados = Trabajo.count

    end

    @total_registros = Trabajo.count

    respond_to do |f|

      f.js

    end

  end

  def agregar

    @trabajo = Trabajo.new

    respond_to do |f|

      f.js

    end

  end

  def guardar

    valido = true
    @msg = ""
    @trabajo_ok = false

    @trabajo = Trabajo.new()

    @trabajo.descripcion = params[:trabajo][:descripcion].upcase

    if @trabajo.save

      auditoria_nueva("registrar trabajo", "trabajos", @trabajo)
      @trabajo_ok = true

    end

    rescue Exception => exc
      # dispone el mensaje de error
      #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?
        @excep = exc.message.split(':')
        @msg = @excep[3].concat(" "+@excep[4].to_s)

      end

    respond_to do |f|

      f.js

    end

  end

  def eliminar

    valido = true
    @msg = ""

    @trabajo = Trabajo.find(params[:id])

    @trabajo_elim = @trabajo

    if valido

      if @trabajo.destroy

        auditoria_nueva("eliminar trabajo", "trabajos", @trabajo_elim)

        @eliminado = true

      else

        @msg = "ERROR: No se ha podido eliminar el trabajo. Intente más tarde."

      end

    end
    

    respond_to do |f|

      f.js

    end

  end

  def editar

    @trabajo = Trabajo.find(params[:id])

    respond_to do |f|

      f.js

    end

  end

  def actualizar

    valido = true
    @msg = ""

    @trabajo = Trabajo.find(params[:trabajo][:id])
    auditoria_id = auditoria_antes("actualizar trabajo", "trabajos", @trabajo)

    if valido

      @trabajo.descripcion = params[:trabajo][:descripcion].upcase

      if @trabajo.save

        auditoria_despues(@trabajo, auditoria_id)
        @trabajo_ok = true

      end

    end
    rescue Exception => exc
      # dispone el mensaje de error
      #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?

        @excep = exc.message.split(':')
        @msg = @excep[3].concat(" "+@excep[4])

      end

    respond_to do |f|

      f.js

    end

  end




end

app/helpers/trabajos_helper.rb
module TrabajosHelper

  def link_to_editar_trabajo(trabajo)

      render partial: 'link_to_editar_trabajo', locals: { trabajo: trabajo }

  end

end

app/views/trabajos/_agregar.html.erb
<div class="modal-dialog">

  <div class="modal-content">

    <div class="modal-header" style="background:#e6e6e6;">

      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Trabajo</h4>

    </div>

    <%= form_for @trabajo, remote: true, url: trabajos_guardar_url, html: { id: "form-agregar-trabajo" , autocomplete: 'off'}, method: 'POST' do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">

           <div class="col-sm-4"><%= f.label :descripcion, "Descripción #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm',style:"text-transform:uppercase;" %></div>
          <div class="col-sm-1"></div><br />

      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "<span class='glyphicon glyphicon-remove'></span> Cerrar".html_safe, "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %>
        <%= f.submit "Guardar".html_safe, class: "btn btn-primary", id: "btn-guardar-trabajo" %>

      </div>

    <% end %>

  </div>

</div>

<style type="text/css">

  #form-agregar-trabajo label, #form-agregar-trabajo input[type='text'], #form-agregar-trabajo select { float:left; margin-top:5px;}
  #form-agregar-trabajo br {clear:both; }
  #form-agregar-trabajo label { width:200px;font-size:12px;margin-top:10px;}
  #form-agregar-trabajo #descripcion { width:50%;}


</style>

<script type="text/javascript">

  aplicar_datepicker2();

</script>

app/views/trabajos/_editar.html.erb
<div class="modal-dialog" style="text-align:left;">

  <div class="modal-content">

    <div class="modal-header" style="background:#e6e6e6;">

      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Editar Trabajo</h4>

    </div>

    <%= form_for @trabajo, remote: true, url: trabajos_actualizar_url, html: { id: "form-editar-trabajo" }, method: 'POST' do |f| %>

      <%= f.hidden_field :id %>
      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= f.label :descripcion, "Descripción #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm',style:"text-transform:uppercase;" %></div>
          <div class="col-sm-1"></div><br />

      </div>

      <div class="modal-footer" style="background:#e6e6e6;">
        <%= link_to "<span class='glyphicon glyphicon-remove'></span> Cerrar".html_safe, "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %>
        <%= f.submit "Guardar".html_safe, class: "btn btn-primary", id: "btn-guardar-trabajo" %>
      </div>

    <% end %>

  </div>
</div>

<style type="text/css">

  #form-editar-trabajo label, #form-editar-trabajo input[type='text'], #form-editar-trabajo select { float:left; margin-top:5px;}
  #form-editar-trabajo br {clear:both; }
  #form-editar-trabajo label { width:200px;font-size:12px;margin-top:10px;}


</style>

<script type="text/javascript">

  aplicar_datepicker2();

</script>

app/views/trabajos/_link_to_editar_estado_ganado.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-estado-ganado-#{estado_ganado.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar el estado ganado.', onclick: "$('.modal').html('');return false;" %>


<%= modal_window( window_id: "modal-window-editar-estado-ganado", link_to_id: "#link-to-editar-estado-ganado-#{estado_ganado.id}", url: estados_ganados_editar_path( window_id: "modal-window-editar-estado-ganado", id: estado_ganado.id) )%>

app/views/trabajos/_link_to_editar_trabajo.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-trabajo-#{trabajo.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar el estado ganado.', onclick: "$('.modal').html('');return false;" %>


<%= modal_window( window_id: "modal-window-editar-trabajo", link_to_id: "#link-to-editar-trabajo-#{trabajo.id}", url: trabajos_editar_path( window_id: "modal-window-editar-trabajo", id: trabajo.id) )%>

app/views/trabajos/_lista.html.erb
<% if trabajos.present? %>

  <% trabajos.each do |trabajo| %>

    <tr>

      <td><%= trabajo.id %></td>
      <td><%= trabajo.descripcion%></td>
     </td>

      <td style="width:120px;">

        <%= link_to_editar_trabajo(trabajo) %>

        <%= link_to icon_eliminar,"#", onclick: "eliminar_registro(#{trabajo.id});return false;", class: "btn btn-danger btn-xs", id: "btn-eliminar-trabajo", title: 'Haga click para eliminar el Trabajo'  %>

       </td>




      </td>

    </tr>

  <% end %>

<tr id="tab-paginacion">

    <td colspan="12" style="text-align:center;"><div class="flickr_pagination"><%= ajax_will_paginate trabajos, :params => params %></div></td>
</tr>

<tr>
    <td colspan="12">

      Cantidad de registros encontrados: <%= @total_encontrados %>
      
    </td>
</tr>



<% else %>

  <tr>

    <td colspan="12"><p class='none-result'>No se han encontrado resultados.</p></td>

  </tr>


<% end %>


<script type="text/javascript">

  function eliminar_registro(trabajo_id) {

        swal({
          title: "Confirmar",
          text: "Al confirmar se eliminará permanentemente de la lista de Trabajos",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

              $.ajax({
                url: "<%= url_for(trabajos_eliminar_path) %>",
                data: {id: trabajo_id},
                dataType: 'script'
              });

          } else{

            return false;

          }

        });


    }

</script>

app/views/trabajos/agregar.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'agregar')%>");
$("#<%= params[:window_id]%>").modal('show'); 

app/views/trabajos/index.html.erb
<%= javascript_include_tag "sweetalert.min" %>
<%= stylesheet_link_tag "sweetalert" %>
<div>

  <div class="col-sm-12" style="border-bottom: 2px solid #b6b6b6;margin-bottom:5px;padding:0px;">
    <h3 style="float:left;margin-top:5px;">Trabajos</h3>
    <%= link_to "<i class='glyphicon glyphicon-plus-sign'></i> agregar".html_safe, "#", id: "link-to-agregar-trabajo", class: "btn btn-primary pull-right", style: "float:right;margin-left:10px;", onclick: "$('.modal').html('');return false;" %>
    <%= modal_window( window_id: "modal-window-agregar-trabajo", link_to_id: "#link-to-agregar-trabajo", url: trabajos_agregar_path( window_id: "modal-window-agregar-trabajo") )%>

  </div>
</div>

<div style="clear:both;"></div>

<div class="table-responsive" id="table-trabajos">

  <table class="table table-small-font table-bordered table-striped" style="font-size:11px;">

    <thead>

      <%= form_tag trabajos_lista_path, remote: true, id: "form-buscar-trabajos"  do  %>

        <tr>

          <th style="width:15%;">
            <span>ID</span>
            <div class="input-group input-group-sm">
              <%= text_field_tag :form_buscar_trabajos_id, nil, :class => 'form-control', :placeholder => "" %>
              <span class="input-group-addon limpiar" onclick="quitar_filtro('#form-buscar-trabajos', '#form_buscar_trabajos_id');"><i class="fa fa-times"></i></span>
            </div>
          </th>


          <th style="width:25%;">
            <span>Descripción</span>
            <div class="input-group input-group-sm">
                <%= text_field_tag :form_buscar_trabajos_descripcion, nil, :class => 'form-control', :placeholder => "" %>
                <span class="input-group-addon limpiar" onclick="$('#form_buscar_trabajos_id').val('');quitar_filtro('#form-buscar-trabajos', '#form_buscar_trabajos_descripcion');"><i class="fa fa-times"></i></span>
            </div>

            <%#= hidden_field_tag :form_buscar_trabajos_descripcion %>
            <%#= autocomplete_help( ruta:  autocompletar_path(atributo_id: :id,
                  atributo_descripcion: :descripcion,
                  atributo_tipo: :text,
                  model: :EstadoGanado,
                  limit: 10,
                  cadena_consulta: "upper(quitar_acentos(descripcion))",
                  orden: "descripcion"),
              parametro_id: "form_buscar_trabajos_descripcion",
              resultado_id: "form_buscar_trabajos_id",
              min_length: 2
              ) %>
          </th>



          <th style="width:15%;"></th>

        </tr>

        <% end %>

      </thead>

    <tbody id="trabajos-lista"></tbody>

  </table>

</div>




<script type="text/javascript">

  //---------------------------- RECUPERANDO DATOS ----------------------------//
  $("#form-buscar-trabajos").bind("submit", function () {
    var valido = true;
    if($("#form_buscar_trabajos_descripcion").val().length !== 0 ){
      valido = false;
      if(($("#form_buscar_trabajos_descripcion").val().replace(/\s/g,'')).length > 2 && ($("#form_buscar_trabajos_descripcion").val().replace(/\s/g,'')).length > 2){
        valido = true;
      }else{
        valido = false;
        //swal("Para la búsqueda por Nombre y Apellido Ingrese minimo 3(tres) carácteres en cada caja de texto", "", "error");
        $(".nmb").html('*Ingrese minimo 3(tres) carácteres para cada caja de texto');
        $(".nmb").attr({'style':'color: red;font-size: 8px;'});
      }
    }

    if(valido){
    $(".nmb").html('');
    $("#trabajos-lista").html("<%= escape_javascript("<tr><td colspan='9' style='text-align:center;'>#{image_tag('ajax-loader0.gif')}</td></tr>").html_safe %>")
    }



  })

  //---------------------------------------------------------------------------//
  //---------------------------- BUSCAR PERSONAS-------- -------------------------//
  $("#table-trabajos input, #table-trabajos select").bind('change', function () {
      $.ajaxQ.abortAll();
      $("#form-buscar-trabajos").submit();

  })
  //----------------------------------------------------------------------------//
  //----------------------------INICIO -----------------------------------------//
  aplicar_datepicker();
  $("#form-buscar-trabajos").submit();
  <% if params[:agregar] %>
    $("#link-to-agregar-trabajo").trigger('click');
  <% end %>
  //----------------------------------------------------------------------------//
</script>

<style>
    /*INTRO.JS*/
    .introjs-helperNumberLayer{
        width: 23px;
        height: 23px;
        padding: 0px;
    }

    #start-tour{
        cursor: pointer;
    }

    #form-buscar-trabajos table th { background:#e6e6e6;}
    #form-buscar-trabajos table th span.limpiar { background:#fff;}

</style>

app/views/trabajos/lista.js.erb
$("#trabajos-lista").html("<%= escape_javascript(render partial: "lista", locals: { trabajos: @trabajos }) %>");