config/routes.rb
Rails.application.routes.draw do


  namespace 'api' do
    namespace 'v1' do

      resources :personas
      resources :usuarios

    end
  end
  
  #WEB SERVICES 
  namespace :api, defaults: { format: "json" } do
  
    namespace :v1 do
  
      resources :web_service_user
      post '/api/v1/web_service_user/index'
      
      resources :web_service_recovery
      post '/api/v1/web_service_recovery/index'

      resources :web_service_ganado
      get '/api/v1/web_service_ganado/index'

      resources :web_service_medicamento
      get '/api/v1/web_service_medicamento/index'

      resources :web_service_alimento
      get '/api/v1/web_service_alimento/index'

      resources :web_service_hacienda
      get '/api/v1/web_service_hacienda/index'

      resources :web_service_potrero
      get '/api/v1/web_service_potrero/index'

      resources :web_service_control_ganado
      post '/api/v1/web_service_control_ganado/index'


    end
  
  end


#-------------------------BLOQUE TAREAS AUTOMATICAS------------------------
#CRONTAB
get 'crontab_ultron/index'
#--------------------------------------------------------------------------

#----------------------------INICIO BLOQUE DE RUTAS GANATEC-----------------------
#NOTIFICACIONES
  post 'notificaciones_personas/lista'
  get 'notificaciones_personas/lista'
  get 'notificaciones_personas/agregar'
  post 'notificaciones_personas/guardar'
  get 'notificaciones_personas/eliminar'
  get 'notificaciones_personas/editar'
  post 'notificaciones_personas/actualizar'
  get 'notificaciones_personas/index'
  get 'notificaciones_personas/activar_notificacion'


#GANADOS FAENAS
  get 'ganados_faenas/index'
  post 'ganados_faenas/lista'
  get 'ganados_faenas/lista'
  get 'ganados_faenas/agregar'
  post 'ganados_faenas/guardar'
  get 'ganados_faenas/eliminar_ganado_faena'
  get 'ganados_faenas/crear_lote_ganado'
  post 'ganados_faenas/crear_lote_ganado'
  post 'ganados_faenas/lista_ganado'
  get 'ganados_faenas/lista_ganado'
  get 'ganados_faenas/agregar_ganado_lote'
  get 'ganados_faenas/eliminar_ganado_lote'
  get 'ganados_faenas/seleccionar_lote'
  post 'ganados_faenas/eliminar_lote'
  get 'ganados_faenas/buscar_cliente'
  get 'ganados_faenas/buscar_ganado'
  get 'ganados_faenas/ganado_faena_detalle'

#INFO GASTOS
  get 'info_gastos/index'
  post 'info_gastos/lista'
  get 'info_gastos/lista'
  get 'info_gastos/exportar_pdf'

#INFO COMPRAS
  get 'info_compras/index'
  post 'info_compras/lista'
  get 'info_compras/lista'
  get 'info_compras/exportar_pdf'
  post 'info_compras/exportar_pdf'

#INFO VENTAS
  get 'info_ventas/index'
  post 'info_ventas/lista'
  get 'info_ventas/lista'
  get 'info_ventas/exportar_pdf'

#GANADOS MUERTOS
  get 'ganados_muertos/index'
  post 'ganados_muertos/lista'
  get 'ganados_muertos/lista'
  get 'ganados_muertos/exportar_pdf'
  
#CARGOS
  post 'cargos/lista'
  get 'cargos/lista'
  get 'cargos/agregar'
  post 'cargos/guardar'
  get 'cargos/eliminar'
  get 'cargos/editar'
  post 'cargos/actualizar'
  get 'cargos/index'

#REMUNERACIONES EXTRAS
  post 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/lista'
  get 'pagos_remuneraciones_extras/agregar'
  post 'pagos_remuneraciones_extras/guardar'
  get 'pagos_remuneraciones_extras/eliminar'
  get 'pagos_remuneraciones_extras/editar'
  post 'pagos_remuneraciones_extras/actualizar'
  get 'pagos_remuneraciones_extras/index'

#DESCUENTOS
  post 'pagos_descuentos/lista'
  get 'pagos_descuentos/lista'
  get 'pagos_descuentos/agregar'
  post 'pagos_descuentos/guardar'
  get 'pagos_descuentos/eliminar'
  get 'pagos_descuentos/editar'
  post 'pagos_descuentos/actualizar'
  get 'pagos_descuentos/index'

#ADELANTOS
  post 'pagos_adelantos/lista'
  get 'pagos_adelantos/lista'
  get 'pagos_adelantos/agregar'
  post 'pagos_adelantos/guardar'
  get 'pagos_adelantos/eliminar'
  get 'pagos_adelantos/editar'
  post 'pagos_adelantos/actualizar'
  get 'pagos_adelantos/index'

#PAGOS DE SALARIOS
  get 'pagos_salarios/index'
  post 'pagos_salarios/lista'
  get 'pagos_salarios/lista'
  get 'pagos_salarios/agregar'
  post 'pagos_salarios/guardar'
  get 'pagos_salarios/eliminar'
  get 'pagos_salarios/salario_detalle'
  
  #MATERIALES
  get 'materiales/index'
  post 'materiales/lista'
  get 'materiales/lista'
  get 'materiales/agregar'
  post 'materiales/guardar'
  get 'materiales/editar'
  post 'materiales/actualizar'
  get 'materiales/eliminar'
  get 'materiales/buscar_material'
  get 'materiales/material_detalle'
  get 'materiales/agregar_material_detalle'
  post 'materiales/guardar_material_detalle'
  get 'materiales/eliminar_material_detalle'


  #TRABAJOS
  get 'trabajos/index'
  post 'trabajos/lista'
  get 'trabajos/lista'
  get 'trabajos/agregar'
  post 'trabajos/guardar'
  get 'trabajos/editar'
  post 'trabajos/actualizar'
  get 'trabajos/eliminar'


  #ORDENES TRABAJOS
  get 'ordenes_trabajos/index'
  post 'ordenes_trabajos/lista'
  get 'ordenes_trabajos/lista'
  get 'ordenes_trabajos/agregar'
  post 'ordenes_trabajos/guardar'
  get 'ordenes_trabajos/editar'
  post 'ordenes_trabajos/actualizar'
  get 'ordenes_trabajos/eliminar'
  get 'ordenes_trabajos/trabajos_detalles'
  get 'ordenes_trabajos/agregar_material_trabajo'
  post 'ordenes_trabajos/guardar_material_trabajo'
  get 'ordenes_trabajos/eliminar_material_trabajo'


#REGISTROS DE GASTOS
  post 'registros_gastos/lista'
  get 'registros_gastos/lista'
  get 'registros_gastos/agregar'
  post 'registros_gastos/guardar'
  get 'registros_gastos/eliminar'
  get 'registros_gastos/editar'
  post 'registros_gastos/actualizar'
  get 'registros_gastos/index'
  

#PERSONALES
  post 'personales/lista'
  get 'personales/lista'
  get 'personales/agregar'
  post 'personales/guardar'
  get 'personales/eliminar'
  get 'personales/editar'
  post 'personales/actualizar'
  get 'personales/index'
  get 'personales/buscar_personal'

  #RAZAS
  get 'razas/index'
  post 'razas/lista'
  get 'razas/lista'
  get 'razas/agregar'
  post 'razas/guardar'
  get 'razas/editar'
  post 'razas/actualizar'
  get 'razas/eliminar'
  get 'razas/buscar_raza'

  #HACIENDAS
  get 'haciendas/index'
  post 'haciendas/lista'
  get 'haciendas/lista'
  get 'haciendas/agregar'
  post 'haciendas/guardar'
  get 'haciendas/editar'
  post 'haciendas/actualizar'
  get 'haciendas/eliminar'
  get 'haciendas/buscar_jurisdiccion'
  get 'haciendas/haciendas_detalles'
  get 'haciendas/agregar_hacienda_detalle'
  post 'haciendas/guardar_hacienda_detalle'
  get 'haciendas/eliminar_hacienda_detalle'
  get 'haciendas/obtener_potreros'

  #POTREROS
  get 'potreros/index'
  post 'potreros/lista'
  get 'potreros/lista'
  get 'potreros/agregar'
  post 'potreros/guardar'
  get 'potreros/editar'
  post 'potreros/actualizar'
  get 'potreros/eliminar'
  get 'potreros/potrero_detalle'
  get 'potreros/agregar_potrero_detalle'
  post 'potreros/guardar_potrero_detalle'
  get 'potreros/eliminar_potrero_detalle'
  get 'potreros/potrero_geocerca'

  #GANADOS
  get 'ganados/index'
  post 'ganados/lista'
  get 'ganados/lista'
  get 'ganados/agregar'
  post 'ganados/guardar'
  get 'ganados/editar'
  post 'ganados/actualizar'
  get 'ganados/eliminar'
  get 'ganados/ganado_detalle'
  get 'ganados/obtener_etapa_ganado'
  get 'ganados/buscar_rp_padre'
  get 'ganados/buscar_rp_madre'
  get 'ganados/agregar_control_sanitario'
  post 'ganados/guardar_control_sanitario'
  get 'ganados/eliminar_control_sanitario'
  get 'ganados/agregar_control_alimentacion'
  post 'ganados/guardar_control_alimentacion'
  get 'ganados/eliminar_control_alimentacion'
  get 'ganados/adjuntar_archivo'
  post 'ganados/guardar_archivo_adjunto'
  get 'ganados/agregar_celo'
  post 'ganados/guardar_celo'
  get 'ganados/buscar_ganado'
  get 'ganados/agregar_lote_ganado'
  post 'ganados/guardar_lote_ganado'
  get 'ganados/marcar_con_enfermedad'
  post 'ganados/guardar_ganado_enfermedad'
  get 'ganados/marcar_como_muerto'
  post 'ganados/guardar_ganado_muerto'
  get 'ganados/marcar_como_produccion'
  get 'ganados/historial_ganado'


  #MEDICAMENTOS
  get 'medicamentos/index'
  post 'medicamentos/lista'
  get 'medicamentos/lista'
  get 'medicamentos/agregar'
  post 'medicamentos/guardar'
  get 'medicamentos/editar'
  post 'medicamentos/actualizar'
  get 'medicamentos/eliminar'
  get 'medicamentos/buscar_medicamento'
  get 'medicamentos/medicamento_detalle'
  get 'medicamentos/agregar_medicamento_detalle'
  post 'medicamentos/guardar_medicamento_detalle'
  get 'medicamentos/eliminar_medicamento_detalle'
  get 'medicamentos/dar_baja_medicamento'
  post 'medicamentos/guardar_baja_medicamento'

  #ALIMENTOS
  get 'alimentaciones/index'
  post 'alimentaciones/lista'
  get 'alimentaciones/lista'
  get 'alimentaciones/agregar'
  post 'alimentaciones/guardar'
  get 'alimentaciones/editar'
  post 'alimentaciones/actualizar'
  get 'alimentaciones/eliminar'
  get 'alimentaciones/buscar_alimentacion'
  get 'alimentaciones/alimentacion_detalle'
  get 'alimentaciones/agregar_alimentacion_detalle'
  post 'alimentaciones/guardar_alimentacion_detalle'
  get 'alimentaciones/eliminar_alimentacion_detalle'

  #CELOS
  get 'celos/index'
  post 'celos/lista'
  get 'celos/lista'
  get 'celos/agregar'
  post 'celos/guardar'
  get 'celos/editar'
  post 'celos/actualizar'
  get 'celos/eliminar'
  get 'celos/celos_detalles'
  get 'celos/cambiar_estado_a_en_proceso_fecundacion'
  get 'celos/cambiar_estado_a_en_reproduccion'
  get 'celos/cambiar_estado_a_celo_perdido'
  post 'celos/guardar_cambiar_estado_a_en_proceso_fecundacion'
  post 'celos/guardar_cambiar_estado_a_en_reproduccion'
  post 'celos/guardar_cambiar_estado_a_celo_perdido'
  get 'celos/buscar_ganado_reproductor'
  get 'celos/buscar_esperma_reproductor'

  #REPRODUCCIONES
  get 'reproducciones/index'
  post 'reproducciones/lista'
  get 'reproducciones/lista'
  get 'reproducciones/agregar'
  post 'reproducciones/guardar'
  get 'reproducciones/eliminar'
  get 'reproducciones/reproducciones_detalles'

app/controllers/notificaciones_personas_controller.rb
class NotificacionesPersonasController < ApplicationController

	before_filter :require_usuario

	  def index


	  end

	  def lista

	    cond = []
	    args = []

	    if params[:form_buscar_notificaciones_id].present?

	      cond << "id = ?"
	      args << params[:form_buscar_notificaciones_id]

	    end

	    if params[:form_buscar_notificaciones_usuarios_descripcion].present?

	      cond << "descripcion ilike ?"
	      args << "%#{params[:form_buscar_notificaciones_usuarios_descripcion]}%"

	    end

	    if params[:form_buscar_notificaciones_usuarios_nombre_persona].present?

	      cond << "nombre_persona ilike ?"
	      args << "%#{params[:form_buscar_notificaciones_usuarios_nombre_persona]}%"

	    end

	    if params[:form_buscar_notificaciones_usuarios_apellido_persona].present?

	      cond << "apellido ilike ?"
	      args << "%#{params[:form_buscar_notificaciones_usuarios_apellido_persona]}%"

	    end

	    if params[:form_buscar_notificaciones_usuarios_email].present?

	      cond << "email ilike ?"
	      args << "%#{params[:form_buscar_notificaciones_usuarios_email]}%"

	    end

	    

	    cond = cond.join(" and ").lines.to_a + args if cond.size > 0

	    if cond.size > 0

	      @notificaciones_personas =  VNotificacionPersona.orden_01.where(cond).paginate(per_page: 10, page: params[:page])
	      @total_encontrados = VNotificacionPersona.where(cond).count

	    else

	      @notificaciones_personas = VNotificacionPersona.orden_01.paginate(per_page: 10, page: params[:page])
	      @total_encontrados = VNotificacionPersona.count

	    end

	    @total_registros = VNotificacionPersona.count

	    respond_to do |f|

	      f.js

	    end

	  end


	  def agregar

	    @notificacion_persona = NotificacionPersona.new

	    respond_to do |f|

	      f.js

	    end

	  end


	  def guardar

	    @valido = true
	    @msg = ""

	    persona = Persona.where("id = ?", params[:persona_id]).first
	    
	    unless persona.present?

	    	@valido = false
	    	@msg = "La persona no existe. "

	   	end

	   	unless params[:email].present?
	   		
	   		@valido = false
	    	@msg = "Debe agregar un email. "

	   	end

	   	if @valido
	    
		    @notificacion_persona = NotificacionPersona.new()
		    @notificacion_persona.descripcion = params[:descripcion].upcase
		    @notificacion_persona.persona_id = params[:persona_id]
		    @notificacion_persona.email = params[:email]
		    
		    if @notificacion_persona.save

		      auditoria_nueva("registrar Notificacion Persona", "notificaciones_personas", @notificacion_persona)
		      @notificacion_persona_ok = true
		       

		    end   

	    end           
	             

	    respond_to do |f|

	      f.js

	    end

	  end


	  def eliminar

	    valido = true
	    @msg = ""

	    @notificacion_persona = NotificacionPersona.find(params[:id])
		@notificacion_persona_elim = @notificacion_persona

	    if valido

	      	if @notificacion_persona.destroy

		        auditoria_nueva("eliminar Notificacion Persona", "notificaciones_persona", @notificacion_persona)
		        @eliminado = true

	    	end

		end

	    respond_to do |f|

	      f.js

	    end

	  end

	  def editar

	    @notificacion_persona = NotificacionPersona.find(params[:id])

	    respond_to do |f|

	      f.js

	    end

	  end

	  def actualizar

	    @valido = true
	    @msg = ""

	    @notificacion_persona = NotificacionPersona.find(params[:notificacion_persona][:id])
	    auditoria_id = auditoria_antes("actualizar Notificacion Persona", "notificaciones_personas", @notificacion_persona)

	    unless params[:notificacion_persona][:email].present?
	   		
	   		@valido = false
	    	@msg = "Debe agregar un email. "

	   	end

	    if @valido

	      
	    	@notificacion_persona.descripcion = params[:notificacion_persona][:descripcion].upcase
	    	@notificacion_persona.email = params[:notificacion_persona][:email]
	    	@notificacion_persona.estado = params[:notificacion_persona][:estado]
	      	
	      	if @notificacion_persona.save

	      		auditoria_despues(@notificacion_persona, auditoria_id)
	        	@notificacion_persona_ok = true

	      end

	    end           
	        
	    respond_to do |f|

	      f.js

	    end

	  end
	    

end

app/helpers/notificaciones_personas_helper.rb
module NotificacionesPersonasHelper

  def link_to_editar_notificacion_persona(notificacion_persona)

      render partial: 'link_to_editar_notificacion_persona', locals: { notificacion_persona: notificacion_persona }
      
  end

  
end

app/views/notificaciones_personas/_agregar.html.erb
<%= javascript_include_tag "modulos/usuarios.js" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Notificación Usuario</h4>
      
    </div>

    <%= form_for @notificacion_persona, remote: true, url: notificaciones_personas_guardar_url, html: { id: "form-agregar-notificacion-usuario" , autocomplete: 'off'}, method: 'POST' do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>
      <%= hidden_field_tag :persona_id%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Tipo de Documento #{attr_requerido}".html_safe, id: "lbl-tipo-documento-persona" %></div>
          <div class="col-sm-7"><%= collection_select :persona, :tipo_documento_id,  TipoDocumento.habilitados.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nacionalidad #{attr_requerido}".html_safe, id: "lbl-nacionalidad" %></div>
          <div class="col-sm-7"><%= collection_select :persona, :nacionalidad_id, Nacionalidad.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "N° Documento #{attr_requerido}".html_safe, id: "lbl-documento" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_documento, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nombre #{attr_requerido}".html_safe, id: "lbl-nombre" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_nombre, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Apellido #{attr_requerido}".html_safe, id: "lbl-apellido" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_apellido, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Email #{attr_requerido}".html_safe, id: "lbl-email" %></div>
          <div class="col-sm-7"><%= text_field_tag :email, nil,class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Comentario".html_safe %></div>
          <div class="col-sm-7"><%=text_field_tag :descripcion, nil,class: 'form-control input-sm',style:"text-transform:uppercase;" %></div>
          <div class="col-sm-1"></div><br />
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">
        <%= link_to "<span class='glyphicon glyphicon-remove'></span> Cerrar".html_safe, "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Guardar".html_safe, class: "btn btn-primary", id: "btn-guardar-cargo" %>          
      </div>

    <% end %>

  </div>
  
</div>

<style type="text/css">

  #form-agregar-notificacion-usuario label, #form-agregar-notificacion-usuario input[type='text'], #form-agregar-notificacion-usuario select { float:left; margin-top:5px;}
  #form-agregar-notificacion-usuario br {clear:both; }
  #form-agregar-notificacion-usuario label { width:200px;font-size:12px;margin-top:10px;}
  #form-agregar-notificacion-usuario #descripcion { width:50%;}
  

</style>

<script type="text/javascript">

  setTimeout(function(){ 
    $("#persona_documento").focus();
    $("#persona_tipo_documento_id").val(1);
    $("#persona_nacionalidad_id").val(1);
  }, 1000);

  aplicar_datepicker2();

  $("#persona_documento").bind("keydown", function(e){
     
    if(e.keyCode == 13 || e.keyCode == 9){

      buscar_usuario_v2($("#persona_tipo_documento_id").val(), $("#persona_nacionalidad_id").val(), $("#persona_documento").val(), "<%= url_for(usuarios_buscar_persona_path ) %>");
      return false;

    }
 
  })

</script>

app/views/notificaciones_personas/_editar.html.erb
<div class="modal-dialog" style="text-align:left;">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Editar Notificación Persona</h4>
      
    </div>

    <%= form_for @notificacion_persona, remote: true, url: notificaciones_personas_actualizar_url, html: { id: "form-editar-notificacion-usuario" , autocomplete: 'off'}, method: 'POST' do |f| %>

      <%= f.hidden_field :id %>
      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= f.label :email, "Comentario".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :descripcion, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= f.label :email, "Correo #{attr_requerido}".html_safe %></div>
          <div class="col-sm-7"><%= f.text_field :email, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= f.label :active, "Activo ?".html_safe %></div>
          <div class="col-sm-7"><%= f.check_box :estado %></div>
          <div class="col-sm-1"></div><br />
          
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">
        <%= link_to "<span class='glyphicon glyphicon-remove'></span> Cerrar".html_safe, "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Guardar".html_safe, class: "btn btn-primary", id: "btn-guardar-detalle-credito" %>          
      </div>

    <% end %>

  </div>
</div>

<style type="text/css">

  #form-editar-notificacion-usuario label, #form-editar-notificacion-usuario input[type='text'], #form-editar-notificacion-usuario select { float:left; margin-top:5px;}
  #form-editar-notificacion-usuario br {clear:both; }
  #form-editar-notificacion-usuario label { width:200px;font-size:12px;margin-top:10px;}


</style>

<script type="text/javascript">
  aplicar_datepicker2();
</script>

app/views/notificaciones_personas/_link_to_editar_notificacion_persona.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-notificacion-usuario-#{notificacion_persona.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar la Notificación de usuario.', onclick: "$('.modal').html('');return false;" %>


<%= modal_window( window_id: "modal-window-editar-notificacion-usuario", link_to_id: "#link-to-editar-notificacion-usuario-#{notificacion_persona.id}", url: notificaciones_personas_editar_path( window_id: "modal-window-editar-notificacion-usuario", id: notificacion_persona.id) )%>

app/views/notificaciones_personas/_link_to_editar_notificacion_usuario.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-notificacion-usuario-#{notificacion_usuario.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar la Notificación de usuario.', onclick: "$('.modal').html('');return false;" %>


<%= modal_window( window_id: "modal-window-editar-notificacion-usuario", link_to_id: "#link-to-editar-notificacion-usuario-#{notificacion_usuario.id}", url: notificaciones_usuarios_editar_path( window_id: "modal-window-editar-notificacion-usuario", id: notificacion_usuario.id) )%>

app/views/notificaciones_personas/_lista.html.erb
<% if notificaciones_personas.present? %>

  <% notificaciones_personas.each do |nu| %>

    <tr>

      <td ><%= nu.notificacion_persona_id %></td>
      <td ><%= nu.descripcion%></td>
      <td ><%= nu.nombre_persona.upcase%></td>
      <td ><%= nu.apellido_persona.upcase%></td>
      <td ><%= nu.email%></td>
      <%if nu.estado == true%>
      
        <td ><%= 'Activo' %></td>

      <%else%>
      
        <td ><%= 'Inactivo' %></td>

      <%end%>

      <td >
        
        <%= link_to_editar_notificacion_persona(nu) %>

        <%= link_to icon_eliminar, notificaciones_personas_eliminar_path(id: nu.notificacion_persona_id), remote: true, class: "btn btn-danger btn-xs", title: 'Haga click para eliminar la Notificación a la Persona.', data: { confirm: "Está seguro de eliminar la Notificación?"} %>
         
       </td>

      </td>

    </tr>

  <% end %>

<tr id="tab-paginacion">

    <td colspan="12" style="text-align:center;"><div class="flickr_pagination"><%= ajax_will_paginate notificaciones_personas, :params => params %></div></td>
</tr>

<tr>
    <td colspan="12">
      Cantidad de registros encontrados: <%= @total_encontrados %> 
    </td>
</tr>

 

<% else %>

  <tr>

    <td colspan="12"><p class='none-result'>No se han encontrado resultados.</p></td>

  </tr>


<% end %>

app/views/notificaciones_personas/actualizar.js.erb
<% if @notificacion_persona_ok.present? %>

   $("<div class='col-sm-12' id='msg-editar-notificacion-usuario' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Actualizado Exitosamente.</div>").insertBefore("#form-editar-notificacion-usuario");
   
  $("#form_buscar_notificaciones_usuarios_id").val('<%= @notificacion_persona.id %>');
  $("#form_buscar_notificaciones_usuarios_descripcion").val('');
  $("#form_buscar_notificaciones_usuarios_nombre_persona").val('');
  $("#form_buscar_notificaciones_usuarios_apellido_persona").val('');
  $("#form_buscar_notificaciones_usuarios_email").val('');
  
  setTimeout(function(){

  	swal("Actualizado Exitosamente.")
  	$("#<%= params[:window_id]%>").modal('hide'); 
  	$("#form-buscar-notificaciones-usuarios").submit(); 

  }, 1500);

<% else %>

  $("<div class='col-sm-12' id='msg-editar-notificacion-usuario' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'><%= @msg%></div>").insertBefore("#form-editar-notificacion-usuario");
  
  setTimeout(function(){ 

      $("#msg-agregar-notificacion-usuario").hide(); 
      swal("<%=@msg%>")

  }, 3000);

<% end %>

app/views/notificaciones_personas/agregar.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'agregar')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/notificaciones_personas/editar.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'editar')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/notificaciones_personas/lista.js.erb
$("#notificaciones-usuarios-lista").html("<%= escape_javascript(render partial: "lista", locals: { notificaciones_personas: @notificaciones_personas }) %>");